version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciador-de-contatos-frontend
    ports:
      - "80:80"
    restart: always